import {build} from 'esbuild-wasm';
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
if (process.argv.slice(2).some(arg => arg !== '--check')) throw Error('Only --check is supported');
const check = process.argv.includes('--check');
const result = await build({
  absWorkingDir: root,
  entryPoints: ['scripts/html-entry.mjs'],
  bundle: true, minify: true, target: 'es2020', format: 'iife',
  globalName: 'MC_HTML', platform: 'browser', legalComments: 'none', write: false,
  banner: {js: '// Generated by npm run build:html. See THIRD-PARTY.md and adjacent licenses.'}
});
const artifacts = {
  'Html.gs': result.outputFiles[0].contents,
  'LICENSE-parse5.txt': fs.readFileSync(path.join(root, 'node_modules/parse5/LICENSE')),
  'LICENSE-entities.txt': fs.readFileSync(path.join(root, 'node_modules/entities/LICENSE'))
};
for (const [name, bytes] of Object.entries(artifacts)) {
  const target = path.join(root, 'src/vendor', name);
  if (check) {
    if (!fs.readFileSync(target).equals(Buffer.from(bytes))) throw Error('Stale HTML artifact: ' + name);
  } else fs.writeFileSync(target, bytes);
}
console.log(check ? 'HTML bundle and licenses match the locked build.' : 'HTML bundle and licenses generated.');
